-- CreateTable
CREATE TABLE "GEN_USR" (
    "ID_USR" CHAR(8) NOT NULL,
    "NOM_USR" VARCHAR(100) NOT NULL,
    "EMAIL_USR" VARCHAR(150) NOT NULL,
    "PWD_USR" VARCHAR(255) NOT NULL,
    "ROL_USR" VARCHAR(20) NOT NULL,
    "ACT_USR" BOOLEAN NOT NULL DEFAULT true,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_ACT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GEN_USR_pkey" PRIMARY KEY ("ID_USR")
);

-- CreateTable
CREATE TABLE "VEN_CLI" (
    "ID_CLI" CHAR(8) NOT NULL,
    "NOM_CLI" VARCHAR(150) NOT NULL,
    "REF_CLI" VARCHAR(200),
    "TEL_CLI" VARCHAR(20),
    "DIR_CLI" VARCHAR(250),
    "LIM_MON_CLI" DECIMAL(10,2),
    "LIM_DIA_CLI" INTEGER,
    "ACT_CLI" BOOLEAN NOT NULL DEFAULT true,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_ACT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VEN_CLI_pkey" PRIMARY KEY ("ID_CLI")
);

-- CreateTable
CREATE TABLE "VEN_CAT_PRD" (
    "ID_CAT" SERIAL NOT NULL,
    "NOM_CAT" VARCHAR(100) NOT NULL,
    "DES_CAT" VARCHAR(300),

    CONSTRAINT "VEN_CAT_PRD_pkey" PRIMARY KEY ("ID_CAT")
);

-- CreateTable
CREATE TABLE "VEN_PRD" (
    "ID_PRD" SERIAL NOT NULL,
    "ID_CAT" INTEGER,
    "NOM_PRD" VARCHAR(150) NOT NULL,
    "PRC_STD" DECIMAL(10,2) NOT NULL,
    "ACT_PRD" BOOLEAN NOT NULL DEFAULT true,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_ACT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VEN_PRD_pkey" PRIMARY KEY ("ID_PRD")
);

-- CreateTable
CREATE TABLE "VEN_PPC" (
    "ID_CLI" CHAR(8) NOT NULL,
    "ID_PRD" INTEGER NOT NULL,
    "PRC_PPC" DECIMAL(10,2) NOT NULL,
    "FEC_INI" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ACT_PPC" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "VEN_PPC_pkey" PRIMARY KEY ("ID_CLI","ID_PRD","FEC_INI")
);

-- CreateTable
CREATE TABLE "VEN_PED" (
    "ID_PED" SERIAL NOT NULL,
    "ID_CLI" CHAR(8) NOT NULL,
    "ID_USR_CRE" CHAR(8) NOT NULL,
    "FEC_ENT_PED" DATE NOT NULL,
    "TUR_PED" VARCHAR(6) NOT NULL,
    "EST_PED" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_ACT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VEN_PED_pkey" PRIMARY KEY ("ID_PED")
);

-- CreateTable
CREATE TABLE "VEN_DET_PED" (
    "ID_DET_PED" SERIAL NOT NULL,
    "ID_PED" INTEGER NOT NULL,
    "ID_PRD" INTEGER NOT NULL,
    "CAN" INTEGER NOT NULL,
    "PRC_UNI" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "VEN_DET_PED_pkey" PRIMARY KEY ("ID_DET_PED")
);

-- CreateTable
CREATE TABLE "VEN_ENT" (
    "ID_ENT" SERIAL NOT NULL,
    "ID_PED" INTEGER,
    "ID_CLI" CHAR(8) NOT NULL,
    "ID_USR_REG" CHAR(8) NOT NULL,
    "FEC_ENT" DATE NOT NULL,
    "TUR_ENT" VARCHAR(6) NOT NULL,
    "EST_ENT" VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADA',
    "TOT_ENT" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "OBS_ENT" TEXT,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_ACT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VEN_ENT_pkey" PRIMARY KEY ("ID_ENT")
);

-- CreateTable
CREATE TABLE "VEN_DET_ENT" (
    "ID_DET_ENT" SERIAL NOT NULL,
    "ID_ENT" INTEGER NOT NULL,
    "ID_PRD" INTEGER NOT NULL,
    "CAN" INTEGER NOT NULL,
    "PRC_UNI" DECIMAL(10,2) NOT NULL,
    "SUB_TOT" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "VEN_DET_ENT_pkey" PRIMARY KEY ("ID_DET_ENT")
);

-- CreateTable
CREATE TABLE "VEN_CAM" (
    "ID_CAM" SERIAL NOT NULL,
    "ID_ENT" INTEGER NOT NULL,
    "ID_PRD" INTEGER NOT NULL,
    "CAN" INTEGER NOT NULL,
    "FEC_CAM" DATE NOT NULL,
    "OBS_CAM" TEXT,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VEN_CAM_pkey" PRIMARY KEY ("ID_CAM")
);

-- CreateTable
CREATE TABLE "VEN_PAG" (
    "ID_PAG" SERIAL NOT NULL,
    "ID_CLI" CHAR(8) NOT NULL,
    "ID_USR_REG" CHAR(8) NOT NULL,
    "ID_ENT" INTEGER,
    "MON_PAG" DECIMAL(10,2) NOT NULL,
    "MET_PAG" VARCHAR(20) NOT NULL,
    "FEC_PAG" DATE NOT NULL,
    "OBS_PAG" TEXT,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VEN_PAG_pkey" PRIMARY KEY ("ID_PAG")
);

-- CreateIndex
CREATE UNIQUE INDEX "GEN_USR_EMAIL_USR_key" ON "GEN_USR"("EMAIL_USR");

-- CreateIndex
CREATE INDEX "VEN_PED_ID_CLI_FEC_ENT_PED_idx" ON "VEN_PED"("ID_CLI", "FEC_ENT_PED");

-- CreateIndex
CREATE INDEX "VEN_PED_EST_PED_idx" ON "VEN_PED"("EST_PED");

-- CreateIndex
CREATE INDEX "VEN_DET_PED_ID_PED_idx" ON "VEN_DET_PED"("ID_PED");

-- CreateIndex
CREATE UNIQUE INDEX "VEN_ENT_ID_PED_key" ON "VEN_ENT"("ID_PED");

-- CreateIndex
CREATE INDEX "VEN_ENT_ID_CLI_FEC_ENT_idx" ON "VEN_ENT"("ID_CLI", "FEC_ENT");

-- CreateIndex
CREATE INDEX "VEN_DET_ENT_ID_ENT_idx" ON "VEN_DET_ENT"("ID_ENT");

-- CreateIndex
CREATE INDEX "VEN_CAM_ID_ENT_idx" ON "VEN_CAM"("ID_ENT");

-- CreateIndex
CREATE INDEX "VEN_PAG_ID_CLI_idx" ON "VEN_PAG"("ID_CLI");

-- CreateIndex
CREATE INDEX "VEN_PAG_ID_ENT_idx" ON "VEN_PAG"("ID_ENT");

-- AddForeignKey
ALTER TABLE "VEN_PRD" ADD CONSTRAINT "VEN_PRD_ID_CAT_fkey" FOREIGN KEY ("ID_CAT") REFERENCES "VEN_CAT_PRD"("ID_CAT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PPC" ADD CONSTRAINT "VEN_PPC_ID_CLI_fkey" FOREIGN KEY ("ID_CLI") REFERENCES "VEN_CLI"("ID_CLI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PPC" ADD CONSTRAINT "VEN_PPC_ID_PRD_fkey" FOREIGN KEY ("ID_PRD") REFERENCES "VEN_PRD"("ID_PRD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PED" ADD CONSTRAINT "VEN_PED_ID_CLI_fkey" FOREIGN KEY ("ID_CLI") REFERENCES "VEN_CLI"("ID_CLI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PED" ADD CONSTRAINT "VEN_PED_ID_USR_CRE_fkey" FOREIGN KEY ("ID_USR_CRE") REFERENCES "GEN_USR"("ID_USR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_DET_PED" ADD CONSTRAINT "VEN_DET_PED_ID_PED_fkey" FOREIGN KEY ("ID_PED") REFERENCES "VEN_PED"("ID_PED") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_DET_PED" ADD CONSTRAINT "VEN_DET_PED_ID_PRD_fkey" FOREIGN KEY ("ID_PRD") REFERENCES "VEN_PRD"("ID_PRD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_ENT" ADD CONSTRAINT "VEN_ENT_ID_PED_fkey" FOREIGN KEY ("ID_PED") REFERENCES "VEN_PED"("ID_PED") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_ENT" ADD CONSTRAINT "VEN_ENT_ID_CLI_fkey" FOREIGN KEY ("ID_CLI") REFERENCES "VEN_CLI"("ID_CLI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_ENT" ADD CONSTRAINT "VEN_ENT_ID_USR_REG_fkey" FOREIGN KEY ("ID_USR_REG") REFERENCES "GEN_USR"("ID_USR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_DET_ENT" ADD CONSTRAINT "VEN_DET_ENT_ID_ENT_fkey" FOREIGN KEY ("ID_ENT") REFERENCES "VEN_ENT"("ID_ENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_DET_ENT" ADD CONSTRAINT "VEN_DET_ENT_ID_PRD_fkey" FOREIGN KEY ("ID_PRD") REFERENCES "VEN_PRD"("ID_PRD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_CAM" ADD CONSTRAINT "VEN_CAM_ID_ENT_fkey" FOREIGN KEY ("ID_ENT") REFERENCES "VEN_ENT"("ID_ENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_CAM" ADD CONSTRAINT "VEN_CAM_ID_PRD_fkey" FOREIGN KEY ("ID_PRD") REFERENCES "VEN_PRD"("ID_PRD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PAG" ADD CONSTRAINT "VEN_PAG_ID_CLI_fkey" FOREIGN KEY ("ID_CLI") REFERENCES "VEN_CLI"("ID_CLI") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PAG" ADD CONSTRAINT "VEN_PAG_ID_USR_REG_fkey" FOREIGN KEY ("ID_USR_REG") REFERENCES "GEN_USR"("ID_USR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VEN_PAG" ADD CONSTRAINT "VEN_PAG_ID_ENT_fkey" FOREIGN KEY ("ID_ENT") REFERENCES "VEN_ENT"("ID_ENT") ON DELETE SET NULL ON UPDATE CASCADE;
