-- AlterTable
ALTER TABLE "VEN_CLI" ADD COLUMN     "TIP_CLI" VARCHAR(20) NOT NULL DEFAULT 'EXTERNO';

-- CreateTable
CREATE TABLE "VEN_SAL" (
    "ID_SAL" SERIAL NOT NULL,
    "FEC_SAL" DATE NOT NULL,
    "TUR_SAL" VARCHAR(6) NOT NULL,
    "ID_PRD" INTEGER NOT NULL,
    "CAN_SAL" INTEGER NOT NULL,
    "FEC_CRE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VEN_SAL_pkey" PRIMARY KEY ("ID_SAL")
);

-- CreateIndex
CREATE INDEX "VEN_SAL_FEC_SAL_TUR_SAL_idx" ON "VEN_SAL"("FEC_SAL", "TUR_SAL");

-- AddForeignKey
ALTER TABLE "VEN_SAL" ADD CONSTRAINT "VEN_SAL_ID_PRD_fkey" FOREIGN KEY ("ID_PRD") REFERENCES "VEN_PRD"("ID_PRD") ON DELETE RESTRICT ON UPDATE CASCADE;
